source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SYCache_Example', :exclusive => true do
  pod "SYCache", :path => "../"
end

target 'SYCache_Tests', :exclusive => true do
  pod "SYCache", :path => "../"

  
end
